import 'package:coffee_shop/src/features/products/domain/product.dart';

/// Test products to be used until a data source is implemented
const kTestProducts = [
  Product(
    id: '1',
    imageUrl: 'assets/products/americano.jpg',
    title: 'Americano',
    description: 'Lorem ipsum',
    price: 40,
    availableQuantity: 5,
    avgRating: 4.5,
    numRatings: 2,
  ),
  Product(
    id: '2',
    imageUrl: 'assets/products/cappuccino.jpg',
    title: 'Cappuccino',
    description: 'Lorem ipsum',
    price: 50,
    availableQuantity: 5,
    avgRating: 4,
    numRatings: 2,
  ),
  Product(
    id: '3',
    imageUrl: 'assets/products/caramel-macchiato.jpg',
    title: 'Caramel Macchiato',
    description: 'Lorem ipsum',
    price: 55,
    availableQuantity: 5,
    avgRating: 5,
    numRatings: 2,
  ),
  Product(
    id: '4',
    imageUrl: 'assets/products/coffee-latte.jpg',
    title: 'Coffee Latte',
    description: 'Lorem ipsum',
    price: 60,
    availableQuantity: 5,
  ),
  Product(
    id: '5',
    imageUrl: 'assets/products/colombia-huila.jpg',
    title: 'Colombia Huila',
    description: 'Lorem ipsum',
    price: 60,
    availableQuantity: 5,
  ),
  Product(
    id: '6',
    imageUrl: 'assets/products/espresso.jpg',
    title: 'Espresso',
    description: 'Lorem ipsum',
    price: 50,
    availableQuantity: 5,
  ),
  Product(
    id: '7',
    imageUrl: 'assets/products/flavored-coffee-brown-sugar.jpg',
    title: 'Flavored Coffee Brown Sugar',
    description: 'Lorem ipsum',
    price: 60,
    availableQuantity: 5,
  ),
  Product(
    id: '8',
    imageUrl: 'assets/products/flavored-coffee-hazelnut.jpg',
    title: 'Flavored Coffee Hazelnut',
    description: 'Lorem ipsum',
    price: 60,
    availableQuantity: 5,
  ),
  Product(
    id: '9',
    imageUrl: 'assets/products/flavored-coffee-vanilla.jpg',
    title: 'Flavored Coffee Vanilla',
    description: 'Lorem ipsum',
    price: 60,
    availableQuantity: 5,
  ),
  Product(
    id: '10',
    imageUrl: 'assets/products/golden-mandheling.jpg',
    title: 'Golden Mandheling',
    description: 'Lorem ipsum',
    price: 65,
    availableQuantity: 5,
  ),
  Product(
    id: '11',
    imageUrl: 'assets/products/milk-tea-coffee.jpg',
    title: 'Milk Tea Coffee',
    description: 'Lorem ipsum',
    price: 50,
    availableQuantity: 5,
  ),
  Product(
    id: '12',
    imageUrl: 'assets/products/mochacino.jpg',
    title: 'Mochacino',
    description: 'Lorem ipsum',
    price: 55,
    availableQuantity: 5,
  ),
  Product(
    id: '13',
    imageUrl: 'assets/products/specialty-americano.jpg',
    title: 'Specialty Americano',
    description: 'Lorem ipsum',
    price: 65,
    availableQuantity: 5,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/products/specialty-coffee-latte.jpg',
    title: 'Specialty Coffee Latte',
    description: 'Lorem ipsum',
    price: 70,
    availableQuantity: 5,
  ),
];
